import {readFileSync} from 'node:fs';
import {before,after,test} from 'node:test';
import {initializeTestEnvironment,assertSucceeds,assertFails} from '@firebase/rules-unit-testing';
import {doc,deleteDoc,writeBatch,setDoc,getDoc,getDocs,updateDoc,collection,query,where,limit,serverTimestamp,Timestamp} from 'firebase/firestore';
let env;const projectId='demo-tad-advisory';
const db=(uid,verified=true)=>uid?env.authenticatedContext(uid,{email:uid+'@example.org',email_verified:verified}).firestore():env.unauthenticatedContext().firestore();
const data=uid=>({firstName:'Sample',lastName:'Person',email:uid+'@example.org',altEmail:'',phone:'',company:'Example studio',jobTitle:'Designer',location:'',website:'',connection:'board',specialties:'',bio:'',areas:['graphic'],newsletterOptIn:true,accountEmail:uid+'@example.org',createdAt:serverTimestamp(),updatedAt:serverTimestamp(),updatedBy:uid});
before(async()=>{env=await initializeTestEnvironment({projectId,firestore:{host:'127.0.0.1',port:8080,rules:readFileSync('firestore.rules','utf8')}});await env.withSecurityRulesDisabled(async c=>{const d=c.firestore();for(const role of ['admin','faculty'])await setDoc(doc(d,'roles',role),{role});for(const uid of ['member','other','faculty','admin'])await setDoc(doc(d,'profiles',uid),data(uid));await setDoc(doc(d,'memberAdmin','member'),{status:'very-active',notes:'private'});for(const published of [true,false]){const id=published?'public':'draft';await setDoc(doc(d,'albums',id),{title:id,published,eventDate:'2026-09-27'});for(const hidden of [true,false])await setDoc(doc(d,'albums',id,'photos',hidden?'hidden':'visible'),{hidden,position:0,url:'assets/portfolio-review.jpg'});}});});
after(async()=>{await env.cleanup();});
test('anonymous and unverified accounts cannot read or create profiles',async()=>{await assertFails(getDoc(doc(db(),'profiles','member')));await assertFails(getDoc(doc(db('member',false),'profiles','member')));await assertFails(setDoc(doc(db('new',false),'profiles','new'),data('new')));});
test('member can read/edit own profile, never another profile or list',async()=>{const d=db('member');await assertSucceeds(getDoc(doc(d,'profiles','member')));await assertSucceeds(updateDoc(doc(d,'profiles','member'),{company:'New studio',updatedAt:serverTimestamp(),updatedBy:'member'}));await assertFails(getDoc(doc(d,'profiles','other')));await assertFails(getDocs(query(collection(d,'profiles'),limit(250))));await assertFails(updateDoc(doc(d,'profiles','other'),{company:'Bad',updatedAt:serverTimestamp(),updatedBy:'member'}));});
test('new verified accounts can create valid profiles but cannot impersonate other IDs',async()=>{await assertSucceeds(setDoc(doc(db('new'),'profiles','new'),data('new')));await assertFails(setDoc(doc(db('fake'),'profiles','victim'),data('fake')));});
test('member cannot read admin status, set it, or promote themselves',async()=>{const d=db('member');await assertFails(getDoc(doc(d,'memberAdmin','member')));await assertFails(setDoc(doc(d,'memberAdmin','member'),{status:'very-active',notes:'',updatedAt:serverTimestamp(),updatedBy:'member'}));await assertFails(setDoc(doc(d,'roles','member'),{role:'admin',updatedAt:serverTimestamp(),updatedBy:'member'}));await assertFails(updateDoc(doc(d,'profiles','member'),{role:'admin',updatedAt:serverTimestamp(),updatedBy:'member'}));});
test('faculty can view contacts but cannot edit others or status/roles',async()=>{const d=db('faculty');await assertSucceeds(getDocs(query(collection(d,'profiles'),limit(250))));await assertSucceeds(getDoc(doc(d,'memberAdmin','member')));await assertFails(updateDoc(doc(d,'profiles','member'),{company:'Changed',updatedAt:serverTimestamp(),updatedBy:'faculty'}));await assertFails(setDoc(doc(d,'roles','other'),{role:'faculty',updatedAt:serverTimestamp(),updatedBy:'faculty'}));await assertFails(setDoc(doc(d,'memberAdmin','member'),{status:'removed',notes:'',updatedAt:serverTimestamp(),updatedBy:'faculty'}));});
test('admin edits contact/status and grants access but cannot demote own account',async()=>{const d=db('admin');await assertSucceeds(updateDoc(doc(d,'profiles','member'),{company:'Updated',updatedAt:serverTimestamp(),updatedBy:'admin'}));await assertSucceeds(setDoc(doc(d,'memberAdmin','member'),{status:'needs-follow-up',notes:'Follow up',updatedAt:serverTimestamp(),updatedBy:'admin'}));await assertSucceeds(setDoc(doc(d,'roles','other'),{role:'faculty',updatedAt:serverTimestamp(),updatedBy:'admin'}));await assertFails(setDoc(doc(d,'roles','admin'),{role:'member',updatedAt:serverTimestamp(),updatedBy:'admin'}));});
test('profile ownership, timestamp, area and email validation cannot be bypassed',async()=>{const d=db('member');for(const change of [{areas:['made-up']},{areas:['graphic','graphic']},{email:'bad\nheader@example.org'},{createdAt:Timestamp.fromMillis(0)},{accountEmail:'victim@example.org'},{newsletterOptIn:'yes'}])await assertFails(updateDoc(doc(d,'profiles','member'),{...change,updatedAt:serverTimestamp(),updatedBy:'member'}));});
test('only published albums and visible photos are public',async()=>{const d=db();await assertSucceeds(getDoc(doc(d,'albums','public')));await assertSucceeds(getDocs(query(collection(d,'albums'),where('published','==',true),limit(200))));await assertFails(getDocs(query(collection(d,'albums'),limit(200))));await assertFails(getDoc(doc(d,'albums','draft')));await assertSucceeds(getDoc(doc(d,'albums','public','photos','visible')));await assertFails(getDoc(doc(d,'albums','public','photos','hidden')));await assertFails(getDoc(doc(d,'albums','draft','photos','visible')));});
test('faculty and admins create albums; members cannot',async()=>{for(const uid of ['faculty','admin','member']){const d=db(uid),p={title:'Portfolio Review',eventDate:'2026-09-27',location:'BSU',description:'',coverURL:'assets/portfolio-review.jpg',coverAlt:'Portfolio review',published:false,createdBy:uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await (uid==='member'?assertFails:assertSucceeds)(setDoc(doc(d,'albums',uid),p));}});
test('album photos reject unsafe links and malformed data',async()=>{const d=db('faculty'),p={url:'assets/portfolio-review.jpg',alt:'Review',caption:'',credit:'TAD',position:0,hidden:false,updatedAt:serverTimestamp()};await assertSucceeds(setDoc(doc(d,'albums','faculty','photos','safe'),p));await assertFails(setDoc(doc(d,'albums','faculty','photos','unsafe'),{...p,url:'javascript:alert(1)'}));await assertFails(setDoc(doc(db('member'),'albums','faculty','photos','forbidden'),p));});

test('unverified staff cannot access directory or roles; verified faculty can resolve eligibility',async()=>{for(const uid of ['faculty','admin']){await assertFails(getDocs(query(collection(db(uid,false),'profiles'),limit(250))));await assertFails(getDoc(doc(db(uid,false),'roles',uid)));}await assertSucceeds(getDoc(doc(db('faculty'),'roles','admin')));await assertFails(getDoc(doc(db('member'),'roles','admin')));await assertSucceeds(setDoc(doc(db('admin'),'memberAdmin','faculty'),{status:'ineligible',notes:'',updatedAt:serverTimestamp(),updatedBy:'admin'}));});

test('login email sync requires the same owner and verified auth email',async()=>{const d=env.authenticatedContext('member',{email:'personal@example.org',email_verified:true}).firestore();await assertSucceeds(updateDoc(doc(d,'profiles','member'),{accountEmail:'personal@example.org',updatedAt:serverTimestamp(),updatedBy:'member'}));await assertFails(updateDoc(doc(d,'profiles','member'),{accountEmail:'unverified@example.org',updatedAt:serverTimestamp(),updatedBy:'member'}));await assertFails(updateDoc(doc(db('admin'),'profiles','member'),{accountEmail:'admin@example.org',updatedAt:serverTimestamp(),updatedBy:'admin'}));});

test('account deletion is restricted to the recently authenticated owner',async()=>{const uid='delete-test';await env.withSecurityRulesDisabled(async c=>{for(const name of ['profiles','memberAdmin','roles'])await setDoc(doc(c.firestore(),name,uid),{sample:true});});const recent=env.authenticatedContext(uid,{auth_time:Math.floor(Date.now()/1000),email_verified:false}).firestore();const stale=env.authenticatedContext(uid,{auth_time:Math.floor(Date.now()/1000)-3600}).firestore();for(const name of ['profiles','memberAdmin','roles']){await assertFails(deleteDoc(doc(stale,name,uid)));await assertFails(deleteDoc(doc(db('admin'),name,uid)));await assertFails(deleteDoc(doc(recent,name,'other')));}const b=writeBatch(recent);for(const name of ['profiles','memberAdmin','roles'])b.delete(doc(recent,name,uid));await assertSucceeds(b.commit());});
test('active membership can be saved without changing administrative access',async()=>{await assertSucceeds(updateDoc(doc(db('member'),'profiles','member'),{connection:'active',updatedAt:serverTimestamp(),updatedBy:'member'}));});

const inviteData=(loginEmail='invitee@example.org')=>({loginEmail,profile:{...data('admin'),accountEmail:loginEmail,newsletterOptIn:false},createdAt:serverTimestamp(),createdBy:'admin',expiresAt:Timestamp.fromMillis(Date.now()+86400000)});
test('only admins create invitations, with no subscription or privilege grant',async()=>{const p=inviteData();await assertSucceeds(setDoc(doc(db('admin'),'invitations','valid'),p));for(const who of ['faculty','member'])await assertFails(setDoc(doc(db(who),'invitations','bad-'+who),p));await assertFails(setDoc(doc(db('admin'),'invitations','consent'),{...p,profile:{...p.profile,newsletterOptIn:true}}));await assertFails(setDoc(doc(db('admin'),'invitations','role'),{...p,role:'admin'}));await assertFails(setDoc(doc(db('admin'),'invitations','long'),{...p,expiresAt:Timestamp.fromMillis(Date.now()+40*86400000)}));});
test('only the verified invited email can read a live invitation; list is admin-only',async()=>{await assertSucceeds(getDoc(doc(db('invitee'),'invitations','valid')));for(const d of [db(),db('invitee',false),db('other'),db('faculty')])await assertFails(getDoc(doc(d,'invitations','valid')));await assertFails(getDocs(query(collection(db('invitee'),'invitations'),limit(250))));await assertSucceeds(getDocs(query(collection(db('admin'),'invitations'),limit(250))));});
test('claim consumes invitation only with atomic own profile creation',async()=>{const d=db('invitee');await assertFails(deleteDoc(doc(d,'invitations','valid')));const b=writeBatch(d);b.set(doc(d,'profiles','invitee'),data('invitee'));b.delete(doc(d,'invitations','valid'));await assertSucceeds(b.commit());await assertSucceeds(getDoc(doc(d,'profiles','invitee')));await assertFails(setDoc(doc(d,'roles','invitee'),{role:'admin',updatedAt:serverTimestamp(),updatedBy:'invitee'}));});
test('expired and canceled invitations cannot be claimed, and existing profiles are protected',async()=>{await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'invitations','expired'),{...inviteData('expired@example.org'),expiresAt:Timestamp.fromMillis(0)});});await assertFails(getDoc(doc(db('expired'),'invitations','expired')));await assertSucceeds(setDoc(doc(db('admin'),'invitations','cancel'),inviteData('cancel@example.org')));await assertSucceeds(deleteDoc(doc(db('admin'),'invitations','cancel')));await assertFails(deleteDoc(doc(db('cancel'),'invitations','cancel')));await assertSucceeds(setDoc(doc(db('admin'),'invitations','duplicate'),inviteData('other@example.org')));await assertFails(deleteDoc(doc(db('other'),'invitations','duplicate')));});

test('status overrides are writable only by admins',async()=>{const meta={status:'ready-for-contact',notes:'Reviewed',statusOverride:true,updatedAt:serverTimestamp(),updatedBy:'admin'};await assertSucceeds(setDoc(doc(db('admin'),'memberAdmin','faculty'),meta));for(const uid of ['faculty','member'])await assertFails(setDoc(doc(db(uid),'memberAdmin',uid),{...meta,updatedBy:uid}));await assertFails(setDoc(doc(db('admin'),'memberAdmin','faculty'),{...meta,statusOverride:'yes'}));});
