import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {build} from 'esbuild';import {Window} from 'happy-dom';
const mock=`
export class NotConfigured extends Error {};
export let session={user:{uid:'admin',email:'admin@example.invalid',emailVerified:true},role:'admin'};
export const staff=()=>['admin','faculty'].includes(session.role);export const admin=()=>session.role==='admin';
export const connect=async cb=>{window.testSession=async role=>{session.role=role;session.user=role==='guest'?null:{uid:role,email:role+'@example.invalid',emailVerified:true};await cb(session);};await cb(session);};
const p={id:'sample',firstName:'Alex',lastName:'Sample',email:'alex@example.invalid',altEmail:'',company:'Example Studio',phone:'',jobTitle:'Designer',location:'',website:'',connection:'board',specialties:'Motion graphics',bio:'',areas:['graphic','illustration-animation'],newsletterOptIn:true,status:'very-active',notes:''};
export const profile=async()=>p;export const directory=async()=>[p,{...p,id:'another',firstName:'Bailey',lastName:'Example',email:'bailey@example.invalid',areas:['exhibit'],newsletterOptIn:false,status:'waiting-for-reply'}];
export const accountRole=async()=> 'member';export const saveProfile=async p=>{window.savedProfile=p;};
export const saveAdminRecord=async(...args)=>{window.savedAdmin=args;};export const changeRole=async(...args)=>{window.savedRole=args;};
export const logout=async()=>window.testSession('guest');export const register=async()=>{};export const login=async()=>{};export const resetPassword=async()=>{};export const verifyEmail=async()=>{};export const refreshSession=async()=>{};export const changePassword=async()=>{};
export const listAlbums=async()=>[];export const albumPhotos=async()=>[];export const saveAlbum=async p=>{window.savedAlbum=p;return 'new-album';};export const savePhoto=async()=>{};
`;
const js=(await build({entryPoints:['src/portal.js'],bundle:true,format:'iife',write:false,plugins:[{name:'mock-service',setup(b){b.onResolve({filter:/^\.\/service\.js$/},()=>({path:'mock',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:mock,loader:'js'}));}}]})).outputFiles[0].text;
async function open(page){const w=new Window({url:'https://example.invalid/'+page+'.html',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});w.Option=function(text,value){const o=w.document.createElement('option');o.textContent=text;o.value=value;return o;};w.document.write(readFileSync(page+'.html','utf8').replace(/<script.*?<\/script>/gs,''));w.eval(js);await new Promise(r=>setTimeout(r,20));return w;}
test('account shows all ten colored choices and saves multiple interests',async()=>{const w=await open('account');const d=w.document;assert.equal(d.querySelectorAll('#profile-form input[name=areas]').length,10);assert.equal(d.querySelectorAll('#profile-form input[name=areas]:checked').length,2);assert.equal(d.querySelector('#profile-panel').hidden,false);d.querySelector('#profile-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,20));assert.deepEqual(Array.from(w.savedProfile.areas),['graphic','illustration-animation']);await w.happyDOM.abort();});
test('directory filters, excludes non-subscribers and exposes admin editing only to admins',async()=>{const w=await open('directory');const d=w.document;assert.equal(d.querySelectorAll('[data-edit]').length,2,d.querySelector('#notice').textContent+' / '+d.querySelector('#directory-rows').textContent+' / '+[...d.querySelectorAll('.filters input,.filters select')].map(x=>[x.id,x.value,x.checked]).join(';'));d.querySelector('#prepare-emails').click();assert.equal(d.querySelector('#email-output').value,'alex@example.invalid');d.querySelector('#email-dialog').close();d.querySelector('#filter-exhibit').checked=true;d.querySelector('#filter-exhibit').dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.querySelectorAll('[data-select]').length,1);assert.ok(d.querySelector('#directory-rows').textContent.includes('Bailey'));await w.testSession('faculty');await new Promise(r=>setTimeout(r,20));assert.equal(d.querySelectorAll('[data-edit]').length,0);await w.testSession('guest');assert.equal(d.querySelector('#directory-panel').hidden,true);assert.equal(d.querySelector('#directory-rows').textContent,'');await w.happyDOM.abort();});
test('album editors available for faculty but hidden for members and visitors',async()=>{const w=await open('albums');const d=w.document;assert.equal(d.querySelectorAll('.album-card').length,1);await w.testSession('faculty');await new Promise(r=>setTimeout(r,20));assert.equal(d.querySelector('#new-album').hidden,false);await w.testSession('member');assert.equal(d.querySelector('#new-album').hidden,true);await w.happyDOM.abort();});
