import * as service from './service.js';
import {AREAS,STATUSES,CONNECTIONS,SITE_PHOTOS,statusFor,connectionName} from './key.js';
import {filterContacts,sortContacts,recipients,csv,validateProfile,imageURL,emailValid} from './model.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], page=document.body.dataset.page;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(message,type='',selector='#notice'){if(selector==='#auth-feedback'&&$('#auth-panel')?.hidden)selector='#verification-feedback';const n=$(selector);n.textContent=message;n.className='notice '+type;n.hidden=!message;}
function friendly(error){return ({'auth/email-already-in-use':'An account already uses that email. Sign in or reset your password.','auth/invalid-credential':'That email and password combination was not recognized.','auth/weak-password':'Please choose a stronger password with at least 8 characters.','auth/too-many-requests':'Too many attempts. Please wait a little and try again.','auth/network-request-failed':'The connection was interrupted. Check your connection and try again.','auth/requires-recent-login':'Please sign out, sign in again, and then try this change again.','permission-denied':'Your account does not have permission for this action. Refresh or sign in again.','unavailable':'The directory is temporarily unavailable. Please try again shortly.'})[error.code] || error.message || 'Something went wrong. Please try again.';}
async function perform(button,work,selector='#notice'){if(button)button.disabled=true;try{await work();}catch(e){notice(friendly(e),'error',selector);}finally{if(button)button.disabled=false;}}
const badge=item=>`<span class="badge" style="background:${item.color};color:${item.ink}">${esc(item.label)}</span>`;
const areasMarkup=values=>AREAS.filter(a=>values?.includes(a.id)).map(badge).join('');
function areaOptions(prefix,values=[]){return AREAS.map(a=>`<label class="area-option" style="--area:${a.color}"><input type="checkbox" name="areas" value="${a.id}" id="${prefix}-${a.id}" ${values.includes(a.id)?'checked':''}><span>${esc(a.label)}${a.description?`<small>${esc(a.description)}</small>`:''}</span></label>`).join('');}
const textFields=[['firstName','First name *','given-name',100],['lastName','Last name *','family-name',100],['email','Contact email *','email',254],['altEmail','Alternate email','email',254],['phone','Phone','tel',50],['company','Company / organization','organization',200],['jobTitle','Job title','organization-title',200],['location','City / region','address-level2',200],['website','Website / professional profile','url',2000]];
function profileFields(target,p={}){
  $(target).innerHTML=`<div class="form-grid">${textFields.map(([name,label,auto,max])=>`<label class="field ${name==='website'?'wide':''}">${label}<input name="${name}" value="${esc(p[name])}" type="${name.toLowerCase().includes('email')?'email':name==='phone'?'tel':name==='website'?'url':'text'}" autocomplete="${auto}" maxlength="${max}" ${['firstName','lastName','email'].includes(name)?'required':''}></label>`).join('')}<label class="field wide">Your connection to TAD *<select name="connection" required><option value="">Choose a connection</option>${CONNECTIONS.filter(c=>c.id!=='board'||p.connection==='board').map(c=>`<option value="${c.id}" ${p.connection===c.id?'selected':''}>${esc(c.label)}</option>`).join('')}</select><span class="hint">Tell us how you would like to participate. Active membership is self-reported; applying does not confirm a board appointment. Newsletter topics follow the areas you check below.</span></label></div><fieldset><legend>Your areas of interest *</legend><p class="hint">Select as many as you like. These areas help us share relevant news and opportunities.</p><div class="area-grid">${areaOptions(target.slice(1),p.areas)}</div></fieldset><div class="form-grid"><label class="field wide">Specialties / interests<input name="specialties" maxlength="500" value="${esc(p.specialties)}" placeholder="For example: motion graphics, ceramics, museum design…"></label><label class="field wide">What would you like to share or contribute?<textarea name="bio" maxlength="2000">${esc(p.bio)}</textarea></label></div><fieldset><legend>Stay in the loop.</legend><label class="check-line"><input type="checkbox" name="newsletterOptIn" ${p.newsletterOptIn?'checked':''}><span>I would like TAD newsletters and opportunities related to my selected areas. I can change this preference at any time.</span></label></fieldset>`;
  $(target+' [name=connection]').value=p.connection||'';
  $(target+' [name=connection]').onchange=e=>{if(e.target.value==='supporter')$(target+' [name=newsletterOptIn]').checked=true;};
}
function formProfile(form){const f=new FormData(form);const p=Object.fromEntries([...textFields.map(([k])=>k),'connection','specialties','bio'].map(k=>[k,String(f.get(k)||'').trim()]));p.email=p.email.toLowerCase();p.altEmail=p.altEmail.toLowerCase();p.areas=f.getAll('areas');p.newsletterOptIn=f.get('newsletterOptIn')==='on';const error=validateProfile(p);if(error)throw Error(error);return p;}
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
$('#sign-out').onclick=()=>perform($('#sign-out'),async()=>{await service.logout();notice('You have signed out.');});
let claimId=null,pendingInvites=[];
const incomingInvite=new URLSearchParams(location.hash.slice(1)).get('invite');
if(page==='account'&&incomingInvite&&/^[A-Za-z0-9]{20}$/.test(incomingInvite))sessionStorage.setItem('tad-invite',incomingInvite);
let connected=false, authMode='register', rows=[],shown=[],selected=new Set(),sortKey='lastName',sortDirection=1,editRecord=null,albums=[],currentAlbum=null,photos=[],emailRows=[],viewVersion=0;
if(page==='account'){
  $('#claim-intro').hidden=!sessionStorage.getItem('tad-invite');
  if(sessionStorage.getItem('tad-invite'))$('#signup-email-hint').textContent='Use the email that received your invitation. After claiming your profile, you can change your login to a personal email.';
  $('#dismiss-invite').onclick=()=>{sessionStorage.removeItem('tad-invite');location.href='account.html';};
  $('#delete-form').onsubmit=e=>{e.preventDefault();perform(e.submitter,async()=>{const f=new FormData(e.target);if(f.get('confirmDelete')!=='on')throw Error('Please confirm that you want to permanently delete your account.');try{await service.deleteAccount(f.get('password'));}finally{e.target.querySelector('[name=password]').value='';}e.target.reset();$('#profile-fields').replaceChildren();notice('Your account and contact profile have been deleted.','success','#auth-feedback');},'#delete-feedback');};
  function mode(next){authMode=next;$('#auth-form').hidden=false;$('#reset-form').hidden=true;$('#tab-register').setAttribute('aria-selected',String(next==='register'));$('#tab-login').setAttribute('aria-selected',String(next==='login'));$('#confirm-password-label').hidden=next==='login';$('#confirm-password-label input').required=next==='register';$('#auth-form [name=password]').autocomplete=next==='register'?'new-password':'current-password';$('#signup-note').hidden=next==='login';$('#signup-email-hint').hidden=next==='login';$('#password-hint').hidden=next==='login';$('#auth-submit').textContent=next==='register'?'Create account':'Sign in';}
  $('#tab-register').onclick=()=>mode('register');$('#tab-login').onclick=()=>mode('login');
  $('#auth-form').onsubmit=e=>{e.preventDefault();perform($('#auth-submit'),async()=>{const f=new FormData(e.target);if(authMode==='register'&&f.get('password')!==f.get('confirmPassword'))throw Error('The passwords do not match.');if(authMode==='register'){await service.register(f.get('email').trim(),f.get('password'));notice('Account created. Check your inbox and junk/spam folder for a verification link.','success','#verification-feedback');}else {const result=await service.login(f.get('email').trim(),f.get('password'));if(!result.user.emailVerified){try{await service.verifyEmail();notice('You are signed in. A verification email has been sent. Check your inbox and junk folder.','success','#verification-feedback');}catch(error){notice('You are signed in, but we could not send the verification email. '+friendly(error)+' Use Send verification email to try again.','error','#verification-feedback');}}}e.target.reset();},'#auth-feedback');};
  $('#forgot-password').onclick=()=>{$('#auth-form').hidden=true;$('#reset-form').hidden=false;};$('#back-to-sign-in').onclick=()=>mode('login');
  $('#reset-form').onsubmit=e=>{e.preventDefault();if(!connected)return;perform(e.submitter,async()=>{await service.resetPassword(new FormData(e.target).get('email').trim());notice('If an account exists for that address, a password reset email will arrive shortly. Check your spam folder too.','success','#reset-feedback');},'#reset-feedback');};
  $('#check-verification').onclick=()=>perform($('#check-verification'),async()=>{await service.refreshSession();if(!service.session.user.emailVerified)notice('Your email has not been verified yet. Open the link in your email, then try again.','','#verification-feedback');},'#verification-feedback');
  $('#resend-verification').onclick=()=>perform($('#resend-verification'),async()=>{await service.verifyEmail();notice('Verification email sent. Check your inbox and junk/spam folder.','success','#verification-feedback');},'#verification-feedback');
  $('#profile-form').onsubmit=e=>{e.preventDefault();perform(e.submitter,async()=>{if(claimId){await service.claimInvitation(claimId,formProfile(e.target));claimId=null;sessionStorage.removeItem('tad-invite');history.replaceState(null,'','account.html');$('#claim-intro').hidden=true;}else await service.saveProfile(formProfile(e.target));notice('Your information has been saved.','success','#profile-feedback');},'#profile-feedback');};
  $('#login-email-form').onsubmit=e=>{e.preventDefault();perform(e.submitter,async()=>{const email=new FormData(e.target).get('email').trim().toLowerCase();if(!emailValid(email))throw Error('Enter a valid email address.');if(email===service.session.user.email.toLowerCase())throw Error('That is already your login email.');await service.changeLoginEmail(email);e.target.reset();notice('Check '+email+' for a verification link, including your junk/spam folder. After verifying, sign out and sign in with your new email and existing password. Your profile and contact email will stay the same.','success','#login-email-feedback');},'#login-email-feedback');};
  $('#password-form').onsubmit=e=>{e.preventDefault();perform(e.submitter,async()=>{const f=new FormData(e.target);if(f.get('password')!==f.get('confirmPassword'))throw Error('The passwords do not match.');await service.changePassword(f.get('password'));e.target.reset();notice('Your password has been changed.','success','#password-feedback');},'#password-feedback');};
}
function filters(){return{search:$('#search').value,status:$('#status-filter').value,connection:$('#connection-filter').value,consent:$('#consent-filter').value,areas:$$('#area-filters input:checked').map(x=>x.value),areaMode:$('#area-mode').value};}
function renderDirectory(){
  shown=sortContacts(filterContacts(rows,filters()),sortKey,sortDirection);
  $('#result-count').textContent=`${shown.length} of ${rows.length} contacts${selected.size?` · ${selected.size} selected`:''}`;
  $('#area-filter-count').textContent=filters().areas.length?`(${filters().areas.length})`:'';
  const columns=[['lastName','Name'],['email','Email'],['company','Organization'],['jobTitle','Job title'],['areas','Program areas'],['status','Status'],['connection','Connection'],['phone','Phone'],['location','Location'],['newsletterOptIn','Newsletter'],['updatedAt','Last updated']];
  $('#directory-head').innerHTML=`<th><input type="checkbox" id="select-all" aria-label="Select all filtered contacts" ${shown.length&&shown.every(r=>selected.has(r.id))?'checked':''}></th>`+columns.map(([k,label])=>`<th aria-sort="${sortKey===k?(sortDirection===1?'ascending':'descending'):'none'}"><button data-sort="${k}">${label}${sortKey===k?(sortDirection===1?' ↑':' ↓'):''}</button></th>`).join('')+(service.admin()?'<th>Edit</th>':'');
  $('#directory-rows').innerHTML=shown.length?shown.map(r=>`<tr><td><input type="checkbox" data-select="${esc(r.id)}" aria-label="Select ${esc(r.firstName+' '+r.lastName)}" ${selected.has(r.id)?'checked':''}></td><td><strong>${esc(r.firstName)} ${esc(r.lastName)}</strong>${r.specialties?`<span class="subline">${esc(r.specialties)}</span>`:''}</td><td>${esc(r.email)}${r.altEmail?`<span class="subline">Alt: ${esc(r.altEmail)}</span>`:''}</td><td>${esc(r.company)}</td><td>${esc(r.jobTitle)}</td><td><div class="badges">${areasMarkup(r.areas)}</div></td><td>${badge(statusFor(r.status))}</td><td>${esc(connectionName(r.connection))}</td><td>${esc(r.phone)}</td><td>${esc(r.location)}</td><td>${r.newsletterOptIn?'Subscribed':'Not subscribed'}</td><td>${r.updatedAt?.toDate?.().toLocaleDateString()||'—'}</td>${service.admin()?`<td><button class="button secondary small" data-edit="${esc(r.id)}">Edit</button></td>`:''}</tr>`).join(''):`<tr><td colspan="${service.admin()?13:12}"><div class="empty">${rows.length?'No contacts match these filters.':'Profiles will appear here as members create accounts and save their information.'}</div></td></tr>`;
  $('#select-all').indeterminate=shown.some(r=>selected.has(r.id))&&!shown.every(r=>selected.has(r.id));
  $('#select-all').onchange=e=>{selected=e.target.checked?new Set(shown.map(r=>r.id)):new Set();renderDirectory();};
  $$('[data-sort]').forEach(b=>b.onclick=()=>{sortDirection=sortKey===b.dataset.sort?-sortDirection:1;sortKey=b.dataset.sort;renderDirectory();});
  $$('[data-select]').forEach(b=>b.onchange=()=>{b.checked?selected.add(b.dataset.select):selected.delete(b.dataset.select);renderDirectory();});
  $$('[data-edit]').forEach(b=>b.onclick=()=>perform(b,()=>openContact(b.dataset.edit)));
  $('#prepare-emails').disabled=!shown.some(r=>selected.has(r.id));$('#select-filtered').disabled=!shown.length;$('#export-csv').disabled=!shown.length;
}
async function loadDirectory(){const version=++viewVersion;$('#loading').hidden=false;const fetched=await service.directory();if(version!==viewVersion||!service.staff())return;rows=fetched;selected.clear();renderDirectory();$('#loading').hidden=true;await renderInvitations();}
async function openContact(id){editRecord=rows.find(r=>r.id===id);profileFields('#edit-profile-fields',editRecord);$('#edit-status').value=editRecord.status;$('#edit-status').disabled=['faculty','admin'].includes(editRecord.role);$('#edit-contact-form [name=notes]').value=editRecord.notes;statusMeaning();notice('','','#edit-notice');$('#role-select').value=await service.accountRole(id);$('#save-role').disabled=id===service.session.user.uid;$('#edit-contact').showModal();}
function statusMeaning(){const s=statusFor($('#edit-status').value);$('#edit-status').style.background=s.color;$('#edit-status').style.color=s.ink;$('#edit-status-meaning').textContent=s.meaning;}

function invitationText(i){const url=new URL('account.html',location.href);url.hash='invite='+i.id;return `Hello ${i.profile.firstName},

We have prepared your TAD Advisory Board contact profile so you will not need to enter everything again.

${url.href}

Open the link, create an account with ${i.loginEmail}, and choose your own password. If you already have a login, sign in instead or use Forgot password. Verify your email (check junk/spam), then return to the invitation to review your information, choose your pathway interests and newsletter preferences, and save. You can change your login email afterward.

This invitation expires ${i.expiresAt.toDate().toLocaleDateString()}. If you cannot access that email, reply so we can replace the invitation.

Thank you,
TAD Advisory Board team`;}
function showInvitation(i){$('#invitation-output').value=invitationText(i);$('#invitation-message').hidden=false;$('#invitation-message').scrollIntoView({block:'nearest'});}
async function renderInvitations(){
  $('#invitation-panel').hidden=!service.admin();
  if(!service.admin()){pendingInvites=[];$('#invitation-list').replaceChildren();$('#invitation-output').value='';$('#invitation-message').hidden=true;return;}
  pendingInvites=await service.pendingInvitations();
  $('#invitation-list').innerHTML=pendingInvites.length?pendingInvites.map(i=>`<div class="session-summary"><div><strong>${esc(i.profile.firstName+' '+i.profile.lastName)}</strong><span class="subline">${esc(i.loginEmail)}</span><span class="hint">${i.expiresAt.toMillis()<Date.now()?'Expired':'Awaiting claim'} · expires ${esc(i.expiresAt.toDate().toLocaleDateString())}</span></div><div class="actions"><button class="button secondary small" data-invite-copy="${esc(i.id)}">Prepare email</button><button class="link-button" data-invite-cancel="${esc(i.id)}">Cancel invitation</button></div></div>`).join(''):'<p class="muted">No invitations awaiting a claim.</p>';
  $$('[data-invite-copy]').forEach(b=>b.onclick=()=>showInvitation(pendingInvites.find(i=>i.id===b.dataset.inviteCopy)));
  $$('[data-invite-cancel]').forEach(b=>b.onclick=()=>perform(b,async()=>{await service.cancelInvitation(b.dataset.inviteCancel);$('#invitation-message').hidden=true;await renderInvitations();notice('Invitation canceled. That link can no longer be claimed.','success','#invitation-feedback');},'#invitation-feedback'));
}

function prepareEmails(){const result=recipients(emailRows,$('#email-purpose').value);$('#email-output').value=result.emails.join('; ');$('#email-summary').textContent=`${result.emails.length} unique recipients · ${result.excluded} excluded because of status, subscription preference, or an invalid email.`;$('#copy-emails').disabled=!result.emails.length;$('#copy-status').textContent='';}
if(page==='directory'){
  $('#new-invitation').onclick=()=>{$('#invitation-form').reset();profileFields('#invitation-fields',{connection:'applicant'});$('#invitation-fields [name=newsletterOptIn]').closest('fieldset').hidden=true;notice('','','#invitation-form-feedback');$('#create-invitation').showModal();};
  $('#invitation-form').onsubmit=e=>{e.preventDefault();perform(e.submitter,async()=>{const p=formProfile(e.target),email=e.target.elements.loginEmail.value.trim().toLowerCase();if(!emailValid(email))throw Error('Enter a valid invitation email.');p.newsletterOptIn=false;const id=await service.createInvitation(p,email);$('#create-invitation').close();await renderInvitations();showInvitation(pendingInvites.find(i=>i.id===id));notice('Profile saved for invitation. Copy the message below and send it from Outlook.','success','#invitation-feedback');},'#invitation-form-feedback');};
  $('#copy-invitation').onclick=()=>perform($('#copy-invitation'),async()=>{try{await navigator.clipboard.writeText($('#invitation-output').value);notice('Copied. Paste into an Outlook email to the invited person.','success','#invitation-feedback');}catch{$('#invitation-output').focus();$('#invitation-output').select();notice('Select and copy the invitation above, then paste into Outlook.','','#invitation-feedback');}},'#invitation-feedback');
  for(const s of STATUSES){$('#status-filter').add(new Option(s.label,s.id));$('#edit-status').add(new Option(s.label,s.id));}
  CONNECTIONS.forEach(c=>$('#connection-filter').add(new Option(c.label,c.id)));$('#status-filter').value='';$('#connection-filter').value='';$('#area-filters').innerHTML=areaOptions('filter');$('#status-key').innerHTML=STATUSES.map(s=>`<div>${badge(s)}<p>${esc(s.meaning)}</p></div>`).join('');
  $$('.filters input,.filters select').forEach(el=>el.addEventListener('input',()=>{selected.clear();renderDirectory();}));
  $('#clear-filters').onclick=()=>{$$('.filters input').forEach(i=>i.type==='checkbox'?i.checked=false:i.value='');$('#status-filter').value='';$('#connection-filter').value='';$('#consent-filter').value='all';selected.clear();renderDirectory();};
  $('#refresh-directory').onclick=()=>perform($('#refresh-directory'),loadDirectory);
  $('#edit-status').onchange=statusMeaning;
  $('#edit-contact-form').onsubmit=e=>{e.preventDefault();perform(e.submitter,async()=>{const p=formProfile(e.target);await service.saveAdminRecord(editRecord.id,p,{status:$('#edit-status').value,notes:e.target.elements.notes.value.trim()},editRecord.updatedAt);await loadDirectory();editRecord=rows.find(r=>r.id===editRecord.id);notice('Contact information and status saved.','success','#edit-notice');},'#edit-notice');};
  $('#save-role').onclick=()=>perform($('#save-role'),async()=>{await service.changeRole(editRecord.id,$('#role-select').value);await loadDirectory();editRecord=rows.find(r=>r.id===editRecord.id);$('#edit-status').value=editRecord.status;$('#edit-status').disabled=['faculty','admin'].includes(editRecord.role);statusMeaning();notice('Account access updated. Faculty and admins are automatically Ineligible for board membership.','success','#role-feedback');},'#role-feedback');
  $('#select-filtered').onclick=()=>{selected=new Set(shown.map(r=>r.id));renderDirectory();};
  $('#prepare-emails').onclick=()=>{emailRows=shown.filter(r=>selected.has(r.id));if(!emailRows.length)return;$('#email-purpose').value='newsletter';prepareEmails();$('#email-dialog').showModal();};$('#email-purpose').onchange=prepareEmails;
  $('#copy-emails').onclick=()=>perform($('#copy-emails'),async()=>{try{await navigator.clipboard.writeText($('#email-output').value);$('#copy-status').textContent='Copied. Paste into Outlook’s Bcc field.';}catch{$('#email-output').focus();$('#email-output').select();$('#copy-status').textContent='Select and copy the addresses above, then paste into Outlook.';}});
  $('#export-csv').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([csv(shown)],{type:'text/csv;charset=utf-8'}));a.href=url;a.download='tad-advisory-contacts.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
}
const starterAlbum={id:'portfolio-highlights',title:'Portfolio review & conversations',eventDate:'',location:'Bemidji State University',description:'A few moments from TAD portfolio reviews and conversations with our creative community.',coverURL:'assets/portfolio-review.jpg',coverAlt:'A TAD portfolio review',published:true,builtin:true};
async function renderAlbums(){
  const fetched=connected?await service.listAlbums():[];albums=[...fetched,starterAlbum];$('#album-count').textContent=`${albums.length} ${albums.length===1?'album':'albums'}`;
  $('#album-grid').innerHTML=albums.map(a=>`<article class="album-card"><a href="albums.html?album=${encodeURIComponent(a.id)}"><img src="${esc(imageURL(a.coverURL))}" alt="${esc(a.coverAlt)}" loading="lazy" referrerpolicy="no-referrer"><div class="copy"><p class="eyebrow">${a.published?'ALBUM':'FACULTY DRAFT'}${a.eventDate?' / '+esc(formatDate(a.eventDate)):''}</p><h2>${esc(a.title)}</h2><p>${esc(a.location)}</p><span class="small">View album →</span></div></a></article>`).join('');
  const id=new URLSearchParams(location.search).get('album');if(id){const a=albums.find(a=>a.id===id);if(a)await openAlbum(a);else notice('This album is unavailable or has not been published.');}
}
function formatDate(date){if(!date)return '';if(/^[0-9]{4}$/.test(date))return date;return new Date(date+'T12:00:00').toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'});}
async function openAlbum(a){currentAlbum=a;$('#album-index').hidden=true;$('#album-detail').hidden=false;$('#album-title').textContent=a.title;$('#album-date').textContent=[formatDate(a.eventDate),a.location].filter(Boolean).join(' / ');$('#album-description').textContent=a.description;$('#edit-album').hidden=!service.staff()||a.builtin;photos=a.builtin?SITE_PHOTOS.slice(1).map((p,i)=>({...p,id:String(i),caption:'',position:i})):await service.albumPhotos(a.id);renderPhotos();}
function renderPhotos(){const visible=photos.filter(p=>!p.hidden);$('#album-photos').innerHTML=visible.length?visible.map(p=>`<figure><button class="image-open" data-photo="${esc(p.id)}" aria-label="Enlarge ${esc(p.alt)}"><img src="${esc(imageURL(p.url))}" alt="${esc(p.alt)}" loading="lazy" referrerpolicy="no-referrer"></button><figcaption>${esc(p.caption)}${p.credit?`<span class="subline muted"> · Photo: ${esc(p.credit)}</span>`:''}</figcaption></figure>`).join(''):'<p class="empty">Photos will be added to this album soon.</p>';$$('[data-photo]').forEach(b=>b.onclick=()=>{const p=photos.find(p=>p.id===b.dataset.photo);$('#lightbox-image').src=imageURL(p.url);$('#lightbox-image').alt=p.alt;$('#lightbox-caption').textContent=p.caption||p.alt;$('#lightbox').showModal();});}
function openAlbumEditor(a=null){currentAlbum=a;$('#album-form').reset();for(const key of ['title','eventDate','location','description','coverURL','coverAlt'])$('#album-form').elements[key].value=a?.[key]||'';$('#album-form').elements.published.checked=a?.published||false;$('#album-editor-title').textContent=a?'Edit album':'Create an album';$('#photo-editor').hidden=!a;notice('','','#album-notice');if(a)renderPhotoEditor();$('#album-editor').showModal();}
async function renderPhotoEditor(){photos=await service.albumPhotos(currentAlbum.id);$('#photo-edit-list').innerHTML=photos.length?photos.map(p=>`<div class="photo-edit-row"><img src="${esc(imageURL(p.url))}" alt="" referrerpolicy="no-referrer"><p>${esc(p.alt)}<br><span class="muted">Position ${p.position}${p.hidden?' · Hidden':''}</span></p><div class="actions"><button class="button secondary small" data-photo-move="${esc(p.id)}" data-step="-1">↑</button><button class="button secondary small" data-photo-move="${esc(p.id)}" data-step="1">↓</button><button class="link-button" data-photo-hide="${esc(p.id)}">${p.hidden?'Restore':'Hide'}</button></div></div>`).join(''):'<p class="hint">Add the first photo below.</p>';$('#add-photo-form').elements.position.value=photos.length?Math.max(...photos.map(p=>p.position))+1:0;
  $$('[data-photo-hide]').forEach(b=>b.onclick=()=>perform(b,async()=>{const p=photos.find(p=>p.id===b.dataset.photoHide);await service.savePhoto(currentAlbum.id,{url:p.url,alt:p.alt,caption:p.caption||'',credit:p.credit||'',position:p.position,hidden:!p.hidden},p.id);await renderPhotoEditor();},'#album-notice'));
  $$('[data-photo-move]').forEach(b=>b.onclick=()=>perform(b,async()=>{const at=photos.findIndex(p=>p.id===b.dataset.photoMove),to=at+Number(b.dataset.step);if(to<0||to>=photos.length)return;[photos[at],photos[to]]=[photos[to],photos[at]];for(const [i,p] of photos.entries())await service.savePhoto(currentAlbum.id,{url:p.url,alt:p.alt,caption:p.caption||'',credit:p.credit||'',position:i,hidden:!!p.hidden},p.id);await renderPhotoEditor();},'#album-notice'));
}
if(page==='albums'){
  $('#new-album').onclick=()=>openAlbumEditor();$('#edit-album').onclick=()=>openAlbumEditor(currentAlbum);
  for(const [target,form,url,alt] of [['#cover-choices','#album-form','coverURL','coverAlt'],['#photo-choices','#add-photo-form','url','alt']]){$(target).innerHTML=SITE_PHOTOS.map((p,i)=>`<button type="button" data-choice="${i}"><img src="${p.url}" alt=""><span>${esc(p.alt)}</span></button>`).join('');$(target).querySelectorAll('button').forEach(b=>b.onclick=()=>{const p=SITE_PHOTOS[Number(b.dataset.choice)];$(form).elements[url].value=p.url;$(form).elements[alt].value=p.alt;});}
  $('#album-form').onsubmit=e=>{e.preventDefault();perform(e.submitter,async()=>{const f=new FormData(e.target);const data=Object.fromEntries(['title','eventDate','location','description','coverURL','coverAlt'].map(k=>[k,String(f.get(k)||'').trim()]));if(!imageURL(data.coverURL))throw Error('Choose an existing site photo or a direct HTTPS image link.');data.published=f.get('published')==='on';const id=await service.saveAlbum(data,currentAlbum?.id);currentAlbum={...currentAlbum,...data,id};$('#photo-editor').hidden=false;$('#album-editor-title').textContent='Edit album';await renderPhotoEditor();notice('Album saved. You can add photos below.','success','#album-notice');},'#album-notice');};
  $('#add-photo-form').onsubmit=e=>{e.preventDefault();perform(e.submitter,async()=>{const f=new FormData(e.target);const data=Object.fromEntries(['url','alt','caption','credit'].map(k=>[k,String(f.get(k)||'').trim()]));if(!imageURL(data.url))throw Error('Use an existing site photo or a direct HTTPS image link.');data.position=Number(f.get('position'));data.hidden=false;await service.savePhoto(currentAlbum.id,data);e.target.reset();await renderPhotoEditor();notice('Photo added.','success','#album-notice');},'#album-notice');};
  $('#album-editor').addEventListener('close',()=>perform(null,renderAlbums));
}
async function sessionChanged(session){
  connected=true;$('#loading').hidden=true;$('#sign-out').hidden=!session.user;$$('[data-staff-link]').forEach(a=>a.hidden=!service.staff());
  if(session.roleError)notice('Your account access could not be checked. Please refresh before continuing.','error');
  if(page==='account'){
    $('#delete-panel').hidden=!session.user;
    $('#auth-submit').disabled=false;$('#auth-panel').hidden=!!session.user;$('#verification-panel').hidden=!session.user||session.user.emailVerified;$('#profile-panel').hidden=!session.user?.emailVerified;
    if(session.user&&!session.user.emailVerified)$('#verification-email').textContent=session.user.email;
    if(session.user?.emailVerified){const p=await service.profile();profileFields('#profile-fields',p||{email:session.user.email});claimId=null;const inviteId=sessionStorage.getItem('tad-invite');if(inviteId){try{const i=await service.invitation(inviteId);if(p)throw Error('You already have a saved profile. We have kept your existing information. Ask the sender to cancel this duplicate invitation.');profileFields('#profile-fields',i.profile);claimId=inviteId;notice('Your prefilled profile is ready. Review it, select your newsletter preference, and save to claim it.','','#profile-feedback');}catch(error){notice('The invitation could not be loaded. Check that you verified the email that received it. '+friendly(error),'error','#profile-feedback');}}$('#signed-in-name').textContent=p?`${p.firstName} ${p.lastName}`:'Your TAD account';$('#signed-in-email').textContent=' · '+session.user.email;$('#access-label').textContent={member:'Member account',faculty:'Faculty',admin:'Administrator'}[session.role];}
  }
  if(page==='directory'){
    $('#directory-gate').hidden=!!service.staff();$('#directory-panel').hidden=!service.staff();
    if(service.staff()){$('#directory-access').textContent=service.admin()?'Administrator · edit contact details and statuses, manage access, and create albums.':'Faculty · view and filter contacts, copy email lists, and create albums. Contact editing is reserved for admins.';await loadDirectory();}else{await renderInvitations();viewVersion++;rows=[];shown=[];selected.clear();$('#directory-rows').replaceChildren();$$('dialog[open]').forEach(d=>d.close());}
  }
  if(page==='albums'){$('#new-album').hidden=!service.staff();await renderAlbums();}
}
service.connect(s=>{sessionChanged(s).catch(e=>notice(friendly(e),'error'));}).catch(async e=>{
  $('#loading').hidden=true;notice(friendly(e),e instanceof service.NotConfigured?'':'error');if(page==='directory')$('#directory-gate').hidden=false;if(page==='albums')await renderAlbums();
});
